theme: jekyll-theme-architect
repository: dco-unesp-bauru/tcc-bcc-2020-1
title: [TCCs de BCC]
description: [Trabalhos de Conclusão de Curso em Bach. em Ciência da Computação da Unesp de Bauru (FC) - 2020 1º semestre]
baseurl: /tcc-bcc-2020-1
gems: ['jekyll-github-metadata']
google_analytics: UA-92166189-1
